### ISSUE TITLE
Failure on npm run build - 'ReferenceError: chrome is not defined'

### ISSUE THREAD

**Issue by danxcraig** [PixievoltNo1/svelte-webext-storage-adapter#17]
**Full output from npm run build**
```
> unverbose-v0-1-2@0.0.1 build
> vite build

The following Vite config options will be overridden by SvelteKit:
  - build.rollupOptions.input
```

_**Vite config explainer**_
_In order to utilize content scripts in  `sveltekit-adapter-chrome-extension` I had to adapt the contents of `vite.config.js ` to:_

```
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';
import { fileURLToPath } from 'url';

export default defineConfig({
	plugins: [sveltekit()],
	build: {
		rollupOptions: {
		  input: {
			background: fileURLToPath(new URL('./static/background.js', import.meta.url)),
			content: fileURLToPath(new URL('./static/contentScript.js', import.meta.url)),
			popup: fileURLToPath(new URL('./static/popup.js', import.meta.url)),
		  }
		}
	},
});
```
**Output Continued**
```
vite v4.1.4 building SSR bundle for production...
✓ 57 modules transformed.
11:15:52 [vite-plugin-svelte] ssr compile done.
package                 files     time     avg
unverbose-v0-1-2            5   89.8ms  18.0ms
Generated an empty chunk: "popup".
The following Vite config options will be overridden by SvelteKit:
  - build.rollupOptions.input

vite v4.1.4 building for production...
✓ 49 modules transformed.
11:15:54 [vite-plugin-svelte] dom compile done.
package                 files    time      avg
unverbose-v0-1-2            5   0.16s   31.2ms
Generated an empty chunk: "popup".
.svelte-kit/output/client/app/version.json                                      0.03 kB
.svelte-kit/output/client/vite-manifest.json                                    4.19 kB
.svelte-kit/output/client/app/immutable/assets/_layout.82edd3f7.css             6.08 kB │ gzip: 1.89 kB
.svelte-kit/output/client/app/immutable/popup.4ed993c7.js                       0.00 kB │ gzip: 0.02 kB
.svelte-kit/output/client/app/immutable/entry/_layout.js.984db11e.js            0.07 kB │ gzip: 0.09 kB
.svelte-kit/output/client/app/immutable/chunks/1.85132bc6.js                    0.08 kB │ gzip: 0.10 kB
.svelte-kit/output/client/app/immutable/chunks/3.1cc83066.js                    0.09 kB │ gzip: 0.10 kB
.svelte-kit/output/client/app/immutable/chunks/2.aee114dd.js                    0.09 kB │ gzip: 0.10 kB
.svelte-kit/output/client/app/immutable/chunks/_layout.da46b06b.js              0.14 kB │ gzip: 0.14 kB
.svelte-kit/output/client/app/immutable/chunks/0.7d33da63.js                    0.14 kB │ gzip: 0.13 kB
.svelte-kit/output/client/app/immutable/chunks/index.d909e896.js                0.44 kB │ gzip: 0.31 kB
.svelte-kit/output/client/app/immutable/entry/_layout.svelte.a62bd89f.js        0.54 kB │ gzip: 0.36 kB
.svelte-kit/output/client/app/immutable/entry/popup-page.svelte.737f962e.js     0.76 kB │ gzip: 0.49 kB
.svelte-kit/output/client/app/immutable/entry/error.svelte.1f935683.js          0.98 kB │ gzip: 0.57 kB
.svelte-kit/output/client/app/immutable/background.fadae7dd.js                  1.18 kB │ gzip: 0.69 kB
.svelte-kit/output/client/app/immutable/chunks/singletons.ea3f92fc.js           2.26 kB │ gzip: 1.19 kB
.svelte-kit/output/client/app/immutable/content.f6559c8c.js                     2.97 kB │ gzip: 1.15 kB
.svelte-kit/output/client/app/immutable/entry/app.2cd77df0.js                   5.91 kB │ gzip: 2.33 kB
.svelte-kit/output/client/app/immutable/chunks/index.74b1bf99.js                7.23 kB │ gzip: 2.93 kB
.svelte-kit/output/client/app/immutable/entry/options-page.svelte.2b22708d.js   8.90 kB │ gzip: 3.64 kB
.svelte-kit/output/client/app/immutable/entry/start.8ae211d8.js                23.11 kB │ gzip: 9.19 kB
ReferenceError: chrome is not defined
    at webextStorageAdapter (file:///.../.svelte-kit/output/server/entries/pages/options/_page.svelte.js:94:5)
    at file:///.../.svelte-kit/output/server/entries/pages/options/_page.svelte.js:161:20
    at Object.$$render (file:///.../.svelte-kit/output/server/chunks/index2.js:156:18)
    at Object.default (file:///.../.svelte-kit/output/server/chunks/internal.js:69:98)
    atfile:///.../.svelte-kit/output/server/entries/pages/_layout.svelte.js:4:42
    at Object.$$render (file:///.../.svelte-kit/output/server/chunks/index2.js:156:18)
    at file:///.../.svelte-kit/output/server/chunks/internal.js:58:101
    at $$render (file:///.../.svelte-kit/output/server/chunks/index2.js:156:18)
    at Object.render (file:///.../.svelte-kit/output/server/chunks/index2.js:164:20)
    at render_response (file:///.../.svelte-kit/output/server/index.js:1244:34)
file:///.../node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:53
                                        throw new Error(format(details));
                                              ^

Error: 500 /options
    at file:///.../node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:53:12
    at save (file:///.../node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:355:4)
    at visit (file:///.../node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:204:3)
[vite-plugin-sveltekit-compile] Failed with code 1
error during build:
Error: Failed with code 1
    at ChildProcess.<anonymous> (file:///.../node_modules/@sveltejs/kit/src/utils/fork.js:68:13)
    at ChildProcess.emit (node:events:526:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

**Comment by PixievoltNo1** [comment]
There's nothing out of the ordinary about how this package accesses the `chrome` object, so the issue lies somewhere else. Unfortunately, I don't know enough about Vite or svelte-adapter-chrome-extension to tell you where. I suggest creating a GitHub repo that demonstrates the error and asking about it on the Svelte Discord server.

One possible issue that does stick out to me is that your build is apparently creating an SSR bundle, when a Chrome extension has no SS to do any R.
